<html>
    <head>
        <title>403 | Access forbidden</title>
        <base href="<?php echo Util::baseUrl(); ?>">
        <link rel="stylesheet" href="assets/css/glowie.css">
        <link rel="shortcut icon" href="assets/images/favicon.png">
        <meta name="viewport" content="width=device-width, height=device-height, user-scalable=no, initial-scale=1">
    </head>
    <body>
        <div class="wrapper">
            <div class="content">
                <div class="inner" style="text-align: center;">
                    <div class="title">403</div>
                    <div class="text">
                        You are not allowed to access this page.
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>