<?php

    # ----------------------
    # DO NOT EDIT THIS FILE!
    # ----------------------
    # This file is responsible for setting up and running your application

    // Setup Glowie application and environment
    require_once('../library/bootstrap.php');
    $glowieConfig = $glowieConfig[getenv('GLOWIE_ENV')];

    // Initialize application
    $app = new Glowie\Rails();
    $app->init();
    
?>