<div class="content">
    <h1>glowie</h1>
    <div class="text">
        <h2>You are ready to create something awesome</h2>
        <div class="menu">
            <a href="https://glowie.gabrielsilva.dev.br" target="_blank">Website</a>
            <a href="https://glowie.gabrielsilva.dev.br/docs" target="_blank">Docs</a>
            <a href="https://github.com/glowieframework" target="_blank">GitHub</a>
            <a href="https://github.com/glowieframework/glowie/discussions" target="_blank">Support</a>
        </div>
        <div class="info">
            Glowie {{ Util::getVersion() }} | PHP {{ phpversion() }}<br>
            Page rendered in {{ $this->getRenderTime() }}
        </div>
    </div>
</div>