<html>
    <head>
        <meta charset="UTF-8">
        <base href="{url('/')}">
        <link rel="stylesheet" href="{asset('css/glowie.css')}">
        <link rel="shortcut icon" href="{asset('images/favicon.png')}">
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
        <title>{{ $this->title }}</title>
    </head>
    <body>
        {content}
    </body>
</html>