<html>
    <head>
        <title><?= $this->title; ?></title>
        <base href="<?= Util::baseUrl(); ?>">
        <link rel="stylesheet" href="assets/css/glowie.css">
        <link rel="shortcut icon" href="assets/images/favicon.png">
        <meta name="viewport" content="width=device-width, height=device-height, user-scalable=no, initial-scale=1">
    </head>
    <body>
        <?= $this->getContent(); ?>
    </body>
</html>